// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe1StjqMcZ6JoWUb-DCRhzQ9V8fUeG2Nc',
    appId: '1:150314562075:web:1049f563a4f97577123ebe',
    messagingSenderId: '150314562075',
    projectId: 'native-ecom-demo',
    authDomain: 'native-ecom-demo.firebaseapp.com',
    storageBucket: 'native-ecom-demo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKCWMVWqBtUiIMfPVwVDbRPkLD69pjrIw',
    appId: '1:150314562075:android:405c3122e4197d1d123ebe',
    messagingSenderId: '150314562075',
    projectId: 'native-ecom-demo',
    storageBucket: 'native-ecom-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYPuMH2j2WOFYqUW0Hr1PUlCVgYGZ4ZNw',
    appId: '1:150314562075:ios:8b44f0cbf5b6a3b5123ebe',
    messagingSenderId: '150314562075',
    projectId: 'native-ecom-demo',
    storageBucket: 'native-ecom-demo.appspot.com',
    iosClientId: '150314562075-f6ff3nipfsatm3r4us2g28g97ljsi7sj.apps.googleusercontent.com',
    iosBundleId: 'com.algolia.flutter-ecom-demo',
  );
}
